Don't run `python .../fastavro/__main__.py` in tests
The __main__.py file is executed via `python -m fastavro`.

Users don't execute __main__.py directly anyway.

When the file is executed by its path,
the directory containing it is prepended to sys.path by default
(unless $PYTHONSAFEPATH is set or `python -P` is used).

When the fastavro directory is first sys.path,
`import types` imports fastvaro/types.py
rather than the standard library types module.

This leads to problems:

    Traceback (most recent call last):
      File ".../fastavro/fastavro/__main__.py", line 3, in <module>
        import json
      File "/usr/lib64/python3.12/json/__init__.py", line 106, in <module>
        from .decoder import JSONDecoder, JSONDecodeError
      File "/usr/lib64/python3.12/json/decoder.py", line 3, in <module>
        import re
      File "/usr/lib64/python3.12/re/__init__.py", line 124, in <module>
        import enum
      File "/usr/lib64/python3.12/enum.py", line 3, in <module>
        from types import MappingProxyType, DynamicClassAttribute
      File ".../fastavro/fastavro/types.py", line 2, in <module>
        from typing import Union, List, Dict
      File "/usr/lib64/python3.12/typing.py", line 27, in <module>
        import contextlib
      File "/usr/lib64/python3.12/contextlib.py", line 7, in <module>
        from functools import wraps
      File "/usr/lib64/python3.12/functools.py", line 22, in <module>
        from types import GenericAlias
    ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (.../fastavro/fastavro/types.py)

This only happens to work accidentally
when the tests are executed on editable installation of fastavro.

The .tox/py312/lib64/python3.12/site-packages/__editable__.fastavro-1.9.0.pth
file triggers an early import of the types module *before*
the parent directory of __main__.py is added to sys.path.
A subsequent import of types then works because it reuses sys.modules["types"].

However, when the tests are executed from an environment without such .pth file,
they explode this way.

We have discovered this in Fedora, where we run the tests slightly differently.

When we had sphinxcontrib_jsmath-1.0.1-py3.12-nspkg.pth installed,
the tests passed. When we removed it, they exploded.