allow decompressing zstandard stream blocks (#575)
* allow decompressing zstandard stream blocks

The zstandard stream API produces zstd frames that don't contain the
uncompressed frame size. `zstd.ZstdDecompressor().decompress(data)` is
not able to decompress these frames:

```
~>  python
Python 3.9.7 (default, Oct 10 2021, 15:13:22)
>>> import zstandard as zstd
>>> data = b"(\265/\375\x00X)\x00\x00\bAAAA"
>>> zstd.ZstdDecompressor().decompress(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
zstd.ZstdError: could not determine content size in frame header
```

The stream-API, however, works:

```
>>> obj = zstd.ZstdDecompressor().decompressobj()
>>> obj.decompress(data)
b'\x08AAAA'
```

I cannot find a reference to streaming APIs vs non-streaming APIs in
the Avro specification, and I suppose the intention is to support
both. The official `avro` for Python does support streaming zstd
frames.

On the compressing side of things, a similar approach may be
appropriate, as this would consume less memory (the uncompressed data
wouldn't need to be in memory). However, I don't know if there are any
disadvantages so I'm leaving that out.

* add test case

* decompressobj in pypy code

* fix formatting

Co-authored-by: scottbelden <scottabelden@gmail.com>